### ISSUE TITLE
Nouvelle erreur: View function mapping. 

### ISSUE THREAD

**Issue by ajaniak** [Chartes-TNAH/Boatlas#17]
@DUREAULT, 

j'ai une nouvelle erreur. Sur Stackoverflow, j'ai lu que ça pouvait venir d'une confusion dans les noms de fonction. J'ai donc changer les noms de mes fonctions, mais le problème persiste. Je n'ose pas trop faire des essais puisque des bouts de ton code sont concernés et en conflit avec des fragments du mien. 

`Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from gazetteer.app import app
  File "/Users/axellejaniak/Documents/master2_ENC_2017-2018/Boatlas/gazetteer/app.py", line 28, in <module>
    from .routes import generic
  File "/Users/axellejaniak/Documents/master2_ENC_2017-2018/Boatlas/gazetteer/routes/generic.py", line 214, in <module>
    @app.route("/creer_biblio", methods=["POST", "GET"])
  File "/Users/axellejaniak/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1080, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/Users/axellejaniak/anaconda3/lib/python3.6/site-packages/flask/app.py", line 64, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/axellejaniak/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1051, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: creer_biblio`

**Comment by ajaniak** [comment]
@DUREAULT, 
j'ai résolu le problème. Si tu dois créer une nouvelle route: peux-tu mettre `@login_required
@app.route`et non `@app.route @login_required`s'il te plait? La deuxième solution crée cette erreur chez moi. Merci :)
